local a, b, c, d, e, f;
a = 12;
b = 34;
c = 56;
d = 78;
e = false;
f = true;
print(c + d);
print(a + b * c / d % e);
print(a .. b ^ c + d % a * b .. c / d - a % b or a);
print(a .. b .. c);
print(a ^ b ^ c);
print(a .. b ^ c .. a ^ b .. c);
print(e or e and f);
print(e or f and f);
print(e and e or f);
print(e and f or f);
print(a == a .. a == b);
print(a == a or a == b);
print(a == a and a == b);
print(a ~= b .. c ~= d);
print(a ~= b or c ~= d);
print(a ~= b and c ~= d);
