#!/bin/sh

me=$0

luac=
luadebug=
luaprofile=
cod=maybe
flags=$HKSCFLAGS
hksc=${HKSC-./hksc}

error()
{
	echo "$me: $*" >&2
	exit 1
}

checknotempty()
{
	var=$1
	opt=$2
	eval "val=\$$var"
	test "x$val" = x && error "You must provide a value with '$opt'"
}

while test "x$1" != x; do
	case $1 in
		--bytecode-file=*) luac=${1#*=};;
		--debug-file=*) luadebug=${1#*=};;
		--profile-file=*) luaprofile=${1#*=};;
		--cod=*) cod=${1#*=};;
	esac
	shift
done

case $cod in
	yes|no|maybe) ;;
	1) cod=yes;;
	0) cod=no;;
	*) echo "invalid use of '--cod'" >&2; exit 1;;
esac

if test ! -e "$hksc" || test ! -x "$hksc"; then
	error \
	"'$hksc' is not a valid executable (set HKSC correctly in the invokation)"
fi

if test "x$cod" = "xmaybe"; then
	codstatus=`"$hksc" --print-config 2>&1 | \
	sed -n 's/^[ 	]*T6[ 	]*extensions[ 	]*\(.*\)$/\1/p'`
	case $codstatus in
		Enabled|enabled) cod=yes;;
		*) cod=no;;
	esac
fi

if test "x$cod" = xyes; then
	checknotempty luac --bytecode-file
	test -e "$luac" || error "$luac does not exist"
	cp -f -- "$luac" "$luac.bk" || exit $?
	if test "$xluadebug" != x; then
		checknotempty luaprofile --profile-file
	fi
	# redump bytecode
	"$hksc" $flags -s "$luac.bk" -o "$luac"
	status=$?
	if test $status = 0 && "x$luadebug" != x; then
		# redump callstackdb and debug info
		"$hksc" $flags --with-debug --debugfile="$luadebug" "$luac.bk" \
		--callstackdb="$luaprofile" -o /dev/null
		status=$?
	fi
	rm -f "$luac.bk"
	exit $status
else
	if test "x$luac" != x; then
		"$hksc" $flags -s "$luac" -o "$luac" || exit $?
	fi
	if test "x$luaprofile" != x; then
		"$hksc" $flags -s=p "$luaprofile" -o "$luaprofile" || exit $?
	fi
	if test "x$luadebug" != x; then
		"$hksc" $flags -s=n "$luadebug" -o "$luadebug" || exit $?
	fi
	exit 0
fi
			

