#!/bin/sh

gen=yes

for opt; do
	case $opt in
		--check) gen=no ;;
		--checksumfile=*) checksumfile=${opt#*=} ;;
	esac
done

checksumfile=${checksumfile-expect.sum}

case $gen in
	yes)
		file=
		for f in *.expect; do
			files="$files ${f%.expect}.lua"
		done
		shasum -U -a 256 $files > "$checksumfile"
		exit $? ;;
	no)
		if test ! -e "$checksumfile"; then
			echo "You need to generate $checksumfile" >&2
			exit 1
		fi
		shasum -a 256 -c "$checksumfile" 2>&1 | {
		while IFS= read -r line; do
			case $line in
				*": FAILED")
					error=1
					expectfile=${line%%:*}
					echo "You need to regenerate ${expectfile%.lua}.expect" >&2
				;;
			esac
		done
		exit $error
		}
		exit $? ;;
esac
