#!/bin/sh

# print all lines that exceed 79 characters

dir=${0%/*}
cd "$dir" || exit

limit=79
x=0

for f in *.c *.h *.def; do
	i=1
	sed 's/\r$//' < "$f" | \
	while IFS= read -r line; do
		len=${#line}
		if test $len -gt $limit; then
			printf '%s:%s (%s characters)\n' "$f" "$i" "$len"
			x=1
		fi
		i=$(($i+1))
	done
done

test $x = 0 && echo "No lines found exceeding line limit"
