#!/bin/sh

# Ensure predictable behavior from utilities with locale-dependent output.
LC_ALL=C
export LC_ALL
LANGUAGE=C
export LANGUAGE

CC=${CC-cc}

TMP=tmp_$$
# alias sed=/usr/bin/sed

{
"$CC" $CFLAGS -MM *.c
# generate .lo targets for library sources
for f in hksclib.c l*.c; do
	"$CC" $CFLAGS -MM -MT ${f%.c}.lo $f
done
} > $TMP

sed -i.bk -e "
	/^# DO NOT DELETE.*$/,/^# (end of Makefile)$/{
	/^# DO NOT DELETE.*$/{G;p;r $TMP
	}; /^# (end of Makefile)$/{H;g;p;}; d;
}" Makefile.in

rm -f $TMP Makefile.in.bk
